name: Docker Build and Push (Redis)

on:
  push:
    branches: [ "main" ]
    # 🎯 FILTRO INDÚSTRIA: Só dispara se houver alteração DENTRO da pasta do Redis
    paths:
      - 'Infra/Redis/**' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          # 🔥 O SEGREDO ESTÁ AQUI: Aponta pro caminho da subpasta do Redis
          context: ./Infra/Redis 
          file: ./Infra/Redis/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/kombi-infra-redis-manager:latest